CREATE TABLE IF NOT EXISTS usuario (
	id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS pessoa(
	id SERIAL PRIMARY KEY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	sexo CHAR(1) NOT NULL,
	data_de_nascimento DATE NOT NULL,
	rg VARCHAR(255) NULL,
	cpf VARCHAR(255) NULL
);